name: Daily Guess

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  daily-guess:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      PANDASCORE_TOKEN: ${{ secrets.PANDASCORE_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run daily guess script
        run: |
          yarn --immutable
          yarn ts-node ./scripts/daily-guess.ts
