name: Daily Guess

on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  daily-guess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run daily guess script
        run: |
          yarn
          ts-node ./scripts/daily-guess.ts
