name: PRs to main
on:
  pull_request:
    branches: [main]
    types: [closed]
jobs:
  merge-main-back-to-preview:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Merge main back to preview
        run: |
          git fetch --unshallow
          git checkout preview
          git rebase origin/main
          git push --force-with-lease
