name: PRs to main
on:
  pull_request:
    branches: [main]
    types: [closed]
jobs:
  merge-main-back-to-preview:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge main back to dev preview
        run: |
          git fetch --unshallow
          git checkout dev
          git pull
          git merge --no-ff master -m "Auto-merge main back to preview"
          git push
